// Generated by scripts/build/gen-lua-builtin.py — DO NOT EDIT.
// Source: deploy/apps/ (the same .lua the Lua Store serves).
// Seeded built-ins: a downloaded <data>/apps/<id>.lua always wins.
#pragma once

struct LuaBuiltinApp { const char* id; const char* name; const char* ver; const char* src; };

static const char kLuaSrc_monitor[] = R"WADALUA(-- RF Monitor (Lua) — live RSSI/noise chart with a dBm axis, link-margin grade,
-- RX rate, radio parameters and the recently-heard feed. The page scrolls, so
-- the whole feed is reachable on short screens.
local ui, sys, mesh, timer = wada.ui, wada.sys, wada.mesh, wada.timer
local C = ui.colors
local app = {}

local RSSI_MIN, RSSI_MAX = -130, -20
local TYPE = { [1]="ADV", [2]="TXT", [3]="ACK", [4]="GRP", [5]="REQ", [6]="RSP", [7]="PTH", [8]="TRC" }
local TCOL = { [1]=0xA784E0, [2]=0x4F9DF7, [3]=0x53C06B, [4]=0x35C9C9, [5]=0xE8A33D, [6]=0xF2793C }

local W, narrow
local legend, chart, metrics, radio_lbl, feed_hdr, feed_rows = nil, nil, nil, nil, nil, {}
local peak, rx0, t0

local function fmt_ago(ms)
  local s = ms // 1000
  if s < 60 then return s .. "s" end
  if s < 3600 then return (s // 60) .. "m" end
  return (s // 3600) .. "h"
end

local function grade(m)
  if m >= 20 then return "excellent", C.good end
  if m >= 10 then return "good",      C.good end
  if m >= 5  then return "fair",      0xE8A33D end
  if m > 0   then return "weak",      C.bad end
  return "no margin", C.bad
end

local function refresh()
  local st = mesh.stats()
  if st.rssi > peak then peak = st.rssi end
  chart:push(1, math.floor(st.rssi))
  chart:push(2, math.floor(st.noise))

  local mg = st.rssi - st.noise
  local gtxt, gcol = grade(mg)
  local mins = math.max((sys.millis() - t0) / 60000, 1 / 60)

  legend:set(string.format("RSSI %.0f   noise %.0f   peak %.0f dBm", st.rssi, st.noise, peak))
  metrics:set(string.format("margin %.0f dB (%s)   RX ~%.0f/min", mg, gtxt, (st.rx_pkts - rx0) / mins))
  metrics:color(gcol)
  radio_lbl:set(string.format("%.3f MHz  SF%d  BW %.0f   %d rx / %d err / %d drop   duty %d%%",
                              st.freq, st.sf, st.bw, st.rx_pkts, st.rx_err, st.rx_dropped, st.duty_pct))

  local log = mesh.rx_log()
  for i = 1, #feed_rows do
    local r = log[i]
    if r then
      local nm = TYPE[r.type] or ("t" .. r.type)
      if narrow then
        feed_rows[i]:set(string.format("%-4s %-3s %4d %5.1f %s", fmt_ago(r.ago_ms), nm, r.rssi, r.snr,
                                       r.hops == 0 and "dir" or (r.hops .. "h")))
      else
        feed_rows[i]:set(string.format("%-5s %-3s  %4d dBm  %5.1f dB  %s", fmt_ago(r.ago_ms), nm, r.rssi, r.snr,
                                       r.hops == 0 and "direct" or (r.hops .. (r.hops == 1 and " hop" or " hops"))))
      end
      feed_rows[i]:color(TCOL[r.type] or C.text)
    else
      feed_rows[i]:set(i == 1 and #log == 0 and "listening - nothing heard yet" or "")
      feed_rows[i]:color(C.sub)
    end
  end
end

function app.on_open(w, h)
  W, narrow = w, w < 280
  ui.scroll(true)                      -- the feed runs past the screen; let it scroll
  local LH12 = ui.text_h(12)           -- real line heights, no guessing
  local st = mesh.stats()
  rx0, t0, peak = st.rx_pkts, sys.millis(), st.rssi

  local y = 4
  legend = ui.label("", 4, y, 12, C.accent); legend:width(w - 10); y = y + LH12 + 4

  local AX, ch_h = 38, narrow and 62 or 76
  chart = ui.chart(w - AX - 8, ch_h, 72, C.accent, C.sub)
  chart:pos(AX, y)
  chart:range(RSSI_MIN, RSSI_MAX)
  chart:axis(3, AX)
  y = y + ch_h + 6

  metrics = ui.label("", 4, y, 12, C.text); metrics:width(w - 10)
  y = y + LH12 * (narrow and 2 or 1) + 3
  radio_lbl = ui.label("", 4, y, 12, C.sub); radio_lbl:width(w - 10)
  y = y + LH12 * (narrow and 3 or 2) + 5

  feed_hdr = ui.label(narrow and "recently heard" or "recently heard (newest first)", 4, y, 12, C.sub)
  feed_hdr:width(w - 10)
  y = y + LH12 + 3
  for i = 1, 16 do                     -- scrolling means we can show the whole ring
    feed_rows[i] = ui.label("", 4, y, 12, C.text)
    feed_rows[i]:width(w - 10)
    y = y + LH12 + 2
  end

  refresh()
  timer.every(1000)
end

function app.on_tick(dt) refresh() end

return app
)WADALUA";
static const char kLuaSrc_airtime[] = R"WADALUA(-- Airtime (Lua) — channel utilization over time: live + average bars with a %
-- axis, rx/tx air split, duty ceiling, tx budget and packet counters.
local ui, sys, mesh, timer = wada.ui, wada.sys, wada.mesh, wada.timer
-- Translate through the device's language table (wada.sys.tr, added for #257).
-- Older firmware has no sys.tr, so fall back to the English string rather than error.
local tr = sys.tr or function(x) return x end
local C = ui.colors
local app = {}

local W, narrow
local head, sub, legend, detail, chart
local base, t0, last
local peak_pct = 0

local function restart_window()
  local st = mesh.stats()
  base = { rx = st.rx_air_s, tx = st.tx_air_s }
  t0 = sys.millis()
  last = { ms = t0, rx = st.rx_air_s, tx = st.tx_air_s }
  peak_pct = 0
  chart:fill(1, 0)
  chart:fill(2, 0)
  head:set(tr("sampling..."))
  head:color(C.accent)
  sys.toast(tr("window restarted"), 900)
end

local function refresh()
  local st = mesh.stats()
  local now = sys.millis()
  local wall = (now - t0) / 1000
  if wall < 0.5 then return end

  local rx_air, tx_air = st.rx_air_s - base.rx, st.tx_air_s - base.tx
  local avg = math.min(100, (rx_air + tx_air) * 100 / wall)

  local dw = (now - last.ms) / 1000
  local live = 0
  if dw > 0 then
    live = math.min(100, ((st.rx_air_s - last.rx) + (st.tx_air_s - last.tx)) * 100 / dw)
  end
  last = { ms = now, rx = st.rx_air_s, tx = st.tx_air_s }
  if live > peak_pct then peak_pct = live end

  chart:push(1, math.floor(live))
  chart:push(2, math.floor(avg))

  head:set(string.format(tr("channel busy %.1f%%"), live))
  head:color(live > 50 and C.bad or live > 20 and 0xE8A33D or C.good)
  sub:set(string.format(tr("avg %.1f%%   peak %.1f%%   over %ds"), avg, peak_pct, math.floor(wall)))
  if narrow then
    detail:set(string.format("air rx %ds / tx %ds\nduty %d%%   budget %dms\ntx %d  rx %d  err %d",
      rx_air, tx_air, st.duty_pct, st.tx_budget_ms, st.tx_pkts, st.rx_pkts, st.rx_err))
  else
    detail:set(string.format("air rx %ds / tx %ds   duty %d%%   budget %dms\ntx %d   rx %d   err %d   drop %d   SF%d",
      rx_air, tx_air, st.duty_pct, st.tx_budget_ms, st.tx_pkts, st.rx_pkts, st.rx_err, st.rx_dropped, st.sf))
  end
end

function app.on_open(w, h)
  W, narrow = w, w < 280
  local LH12, LH16 = ui.text_h(12), ui.text_h(16)

  local y = 2
  head = ui.label(tr("sampling..."), 4, y, 16, C.accent); head:width(w - 86)
  ui.button(tr("Reset"), w - 76, y, 70, 30, function() restart_window() end)   -- top-right
  y = y + LH16 + 4
  sub = ui.label("", 4, y, 12, C.sub); sub:width(w - 10)
  y = y + LH12 + 5

  local AX = 34
  local det_lines = narrow and 3 or 2
  local ch_h = h - y - (det_lines * LH12) - LH12 - 14
  if ch_h < 48 then ch_h = 48 end
  if ch_h > 110 then ch_h = 110 end
  chart = ui.chart(w - AX - 8, ch_h, 60, C.accent, 0x4F9DF7, true)
  chart:pos(AX, y)
  chart:range(0, 100)
  chart:axis(3, AX)
  y = y + ch_h + 4

  legend = ui.label(tr("teal = now   blue = average"), 4, y, 12, C.sub); legend:width(w - 10)
  y = y + LH12 + 2
  detail = ui.label("", 4, y, 12, C.text); detail:width(w - 10)

  local st = mesh.stats()
  base = { rx = st.rx_air_s, tx = st.tx_air_s }
  t0 = sys.millis()
  last = { ms = t0, rx = st.rx_air_s, tx = st.tx_air_s }
  timer.every(1000)
end

function app.on_tick(dt) refresh() end

return app
)WADALUA";
static const char kLuaSrc_sdktest[] = R"WADALUA(-- SDK self-test. Exercises the extended SDK so the results can be read off the
-- screen instead of inferred from a build log. Published to the store as a
-- developer/bench tool.
--
-- 1.2 adds wada.crypto (checked against published RFC vectors, so a PASS here is
-- real evidence and not just "it returned something"), wada.mesh.channels, and
-- wada.mesh.send_dm.
-- 1.3 adds the discovery surface (wada.mesh.discover / discovered), packet
-- identity in rx_log, exact micro-degree coordinates, wada.ui.input and the
-- windowed wada.fs.read.
-- 1.6 adds wada.sd.list: capability reporting, traversal rejection, root
-- metadata, and a nested directory listing when the card contains one.
-- 1.7 adds storage-neutral wada.audio capability and API-shape checks. Playback
-- stays manual so opening the bench test never emits sound unexpectedly.
-- 1.5 uses wada.ui.text_lines() to measure instead of estimating, where the
-- firmware has it. That call was added because of the 1.3 bug below: an app
-- could ask how tall a line is but not how wide, so laying out rows meant
-- guessing whether text would wrap. Falls back to the 1.4 estimate on older
-- firmware, so it still lays out correctly there.
-- 1.4 fixes rows drawing on top of one another. label:width() turns wrapping
-- on, so any line wider than the screen became two lines while the caller still
-- advanced by one, and the next row landed on top. Reported with a photo of the
-- channels line sitting across the contacts line. row() now owns the cursor and
-- advances by the height the text actually needs.
local ui, sys, store, timer = wada.ui, wada.sys, wada.store, wada.timer
local C = ui.colors

local app = {}
local rows, keyline, sendline, dmline, msgline = {}, nil, nil, nil, nil
local discline, inputline = nil, nil
local W = 300

-- row() owns the vertical cursor. Every caller used to pass a y and then add a
-- hand-picked constant, which is only correct while the text fits on one line.
-- An app cannot measure rendered text, so the wrapped line count is estimated
-- from a deliberately pessimistic character width: over-estimating costs a
-- little whitespace, under-estimating overlaps the next row.
local LH, GAP = 14, 3
local cy = 4
local function row(text, color, extra_gap)
  local l = ui.label(text, 6, cy, 12, color or C.text)
  l:width(W - 12)
  rows[#rows + 1] = l
  local n
  if ui.text_lines then
    n = ui.text_lines(tostring(text), W - 12, 12)     -- measured: exact
  else
    local cpl = math.max(16, (W - 12) // 7)           -- older firmware: estimate
    n = 0
    for seg in (tostring(text) .. "\n"):gmatch("(.-)\n") do
      n = n + math.max(1, math.ceil(#seg / cpl))
    end
  end
  cy = cy + math.max(1, n or 1) * LH + GAP + (extra_gap or 0)
  return l
end
local function yn(v) return v and "yes" or "NO" end

function app.on_open(w, h)
  W = w or 300
  ui.scroll(true)
  cy = 4
  local y

  local c = sys.caps()
  row("caps: sdk_ext=" .. yn(c.sdk_ext) .. "  kbd=" .. yn(c.keyboard) ..
         "  touch=" .. yn(c.touch) .. "  sd=" .. yn(c.sd), C.accent)
    row("caps: sd_list=" .. yn(c.sd_list) .. "  discover=" .. yn(c.discover) ..
      "  input=" .. yn(c.input) ..
         "  rx_identity=" .. yn(c.rx_identity), C.accent)
    row("caps: audio=" .. yn(c.audio) .. "  wav=" .. yn(c.audio_wav) ..
           "  mp3=" .. yn(c.audio_mp3) .. "  audio_sd=" .. yn(c.audio_sd), C.accent)
    if c.audio then
      local api_ok = wada.audio and type(wada.audio.play) == "function" and
                     type(wada.audio.pause) == "function" and
                     type(wada.audio.resume) == "function" and
                     type(wada.audio.stop) == "function" and
                     type(wada.audio.status) == "function"
      local status = api_ok and wada.audio.status() or nil
      api_ok = api_ok and type(status) == "table" and type(status.state) == "string"
      row("wada.audio API: " .. (api_ok and ("PASS (" .. status.state .. ")") or "FAIL"),
          api_ok and C.good or C.bad)
    else
      row("wada.audio: unavailable on this board", C.sub)
    end
  row("layout: " .. (ui.text_lines and "measured (ui.text_lines)" or "estimated (older firmware)"),
      ui.text_lines and C.good or C.sub)
  -- crypto: published test vectors, so this is checkable rather than merely alive
  if wada.crypto then
    local hex = wada.crypto.hex
    local k20 = string.rep(string.char(0x0b), 20)
    local checks = {
      { "sha256('abc')", hex(wada.crypto.sha256("abc")),
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad" },
      { "sha1('abc')", hex(wada.crypto.sha1("abc")),
        "a9993e364706816aba3e25717850c26c9cd0d89d" },
      { "hmac_sha1 RFC2202#1", hex(wada.crypto.hmac_sha1(k20, "Hi There")),
        "b617318655057264e28bc0b6fb378c8ef146be00" },
      { "hmac_sha256 RFC4231#1", hex(wada.crypto.hmac_sha256(k20, "Hi There")),
        "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7" },
    }
    local allok = true
    for _, t in ipairs(checks) do
      local ok = (t[2] == t[3])
      if not ok then allok = false end
      row("crypto " .. t[1] .. ": " .. (ok and "PASS" or ("FAIL got " .. tostring(t[2]):sub(1, 16))),
          ok and C.good or C.bad)
    end
    -- The point of having it in C: this loop would blow the instruction budget in Lua.
    local t0 = sys.millis()
    for _ = 1, 200 do wada.crypto.hmac_sha1(k20, "Hi There") end
    row(string.format("crypto: 200 x hmac_sha1 in %d ms%s", sys.millis() - t0,
        allok and "" or "  (VECTORS FAILED)"), allok and C.good or C.bad)
  else
    row("wada.crypto: MISSING", C.bad)
  end

  -- channel discovery
  local chans = wada.mesh.channels and wada.mesh.channels() or nil
  if chans then
    local names = table.concat(chans, ", ")
    row("channels(): " .. #chans .. "  " .. names:sub(1, 60), C.text)
  else
    row("wada.mesh.channels: MISSING", C.bad)
  end

  if not c.sdk_ext then
    row("extended SDK is OFF on this board - stopping here.", C.sub)
    return
  end

  -- contacts, so send_dm has a target to name. 1.3 also checks the pubkey field.
  local cts = wada.mesh.contacts()
  local first = cts[1] and cts[1].name or nil
  row("contacts: " .. #cts .. (first and ("  first=" .. first) or ""), C.text)
  if cts[1] then
    local pk = cts[1].pubkey
    row("contacts[1].pubkey: " .. tostring(pk) ..
           (type(pk) == "string" and #pk == 8 and "  PASS" or "  FAIL"),
        (type(pk) == "string" and #pk == 8) and C.good or C.bad)
  end

  local me = wada.mesh.self()
  row("self: " .. tostring(me.name) .. "  pubkey=" .. tostring(me.pubkey), C.text)
  -- Exact coordinates. Lua's floats here are 32-bit, so an app that logs a track
  -- must use the _e6 integers; this proves they are present and consistent.
  local fix = sys.gps()
  if fix then
    local drift = math.abs(fix.lat_e6 / 1e6 - fix.lat)
    row(string.format("gps: %d,%d e6  alt %dm  %d sats  drift %.6f  %s",
        fix.lat_e6, fix.lon_e6, fix.alt_m or 0, fix.sats, drift,
        drift < 0.001 and "PASS" or "FAIL"), drift < 0.001 and C.good or C.bad)
  else
    row("gps: no fix (normal indoors)", C.sub)
  end

  -- rx_log identity: adverts carry a real public key, addressed frames carry
  -- one-byte hashes, everything else carries nothing. All three are correct.
  local log = wada.mesh.rx_log()
  local withpk, withsrc = 0, 0
  for _, r in ipairs(log) do
    if r.pubkey then withpk = withpk + 1 end
    if r.src then withsrc = withsrc + 1 end
  end
  row(string.format("rx_log: %d frames, %d with a pubkey (adverts), %d with src/dst",
      #log, withpk, withsrc), #log > 0 and C.text or C.sub)
  -- fs: windowed read. Writes once (the 1/sec limit means one write per open).
  if wada.fs then
    local probe = "0123456789abcdef"
    wada.fs.write("sdktest.bin", probe)
    local part, total = wada.fs.read("sdktest.bin", 4, 4)
    local ok = (part == "4567" and total == #probe)
    row("fs.read(name,4,4): " .. tostring(part) .. " total=" .. tostring(total) ..
           (ok and "  PASS" or "  FAIL"), ok and C.good or C.bad)
  end

  -- Physical SD listing is read-only and independently feature-detected. A
  -- supported board with no inserted card is a normal bench state, not a test
  -- failure; API shape and path rejection can still be checked separately.
  if c.sd_list then
    if not wada.sd or not wada.sd.list then
      row("wada.sd.list: MISSING despite caps", C.bad)
    else
      local guard_ok, guard_failure = true, nil
      local bad_paths = { "/..", "/.", "/a/../b", "/a//b", "/a/", "relative", "/a\\b" }
      for _, path in ipairs(bad_paths) do
        local rejected, baderr = wada.sd.list(path)
        if rejected ~= nil or baderr ~= "bad path" then
          guard_ok = false
          guard_failure = path .. " -> " .. tostring(baderr)
          break
        end
      end
      row("sd traversal guard: " .. (guard_ok and "PASS" or ("FAIL " .. guard_failure)),
          guard_ok and C.good or C.bad)

      local entries, err = wada.sd.list("/")
      if not entries then
        local note = err == "busy" and " (retry later)" or " (no readable card)"
        row("sd.list('/'): " .. tostring(err) .. note, C.sub)
      else
        local metadata_ok, first_dir = true, nil
        for _, entry in ipairs(entries) do
          if type(entry.name) ~= "string" or
             (entry.type ~= "file" and entry.type ~= "dir") or
             type(entry.size) ~= "number" or type(entry.mtime) ~= "number" then
            metadata_ok = false
          end
          if not first_dir and entry.type == "dir" then first_dir = entry.name end
        end
        row("sd.list('/'): " .. #entries .. " entries, metadata " ..
               (metadata_ok and "PASS" or "FAIL") ..
               (entries.truncated and " (truncated)" or ""),
            metadata_ok and C.good or C.bad)
        if first_dir then
          local nested, nested_err = wada.sd.list("/" .. first_dir)
          row("sd.list('/" .. first_dir .. "'): " ..
                 (nested and (#nested .. " entries PASS") or ("FAIL " .. tostring(nested_err))),
              nested and C.good or C.bad)
        else
          row("sd nested listing: no directory on card to test", C.sub)
        end
      end
    end
  else
    row("wada.sd.list: unavailable on this board", C.sub)
  end

  sendline = row("mesh.send: not tried yet", C.sub)
  dmline   = row("mesh.send_dm: not tried yet", C.sub)
  msgline  = row("on_message: waiting (needs the read permissions)", C.sub)
  y = cy + 4
  ui.button("Send to Public", 6, y, 120, 30, function()
    local ok, err = wada.mesh.send("Public", "wadamesh SDK self-test")
    sendline:set("mesh.send: " .. tostring(ok) .. "  " .. tostring(err))
    sendline:color(ok and C.good or C.bad)
  end)
  ui.button("DM first contact", 132, y, 130, 30, function()
    if not first then dmline:set("mesh.send_dm: no contacts to target"); dmline:color(C.bad); return end
    local ok, err = wada.mesh.send_dm(first, "wadamesh SDK self-test (DM)")
    dmline:set("mesh.send_dm -> " .. first .. ": " .. tostring(ok) .. "  " .. tostring(err))
    dmline:color(ok and C.good or C.bad)
  end)
  cy = y + 38
  discline  = row("mesh.discover: not tried yet", C.sub)
  inputline = row("ui.input: not tried yet", C.sub)
  -- Probing TRANSMITS and makes every neighbour reply, so it is a button, not
  -- something this app does on open.
  y = cy + 4
  ui.button("Probe", 6, y, 90, 30, function()
    local tag, err = wada.mesh.discover()
    if not tag then
      discline:set("mesh.discover: " .. tostring(err)); discline:color(C.bad); return
    end
    discline:set("mesh.discover: sent, waiting for replies..."); discline:color(C.text)
  end)
  ui.button("Results", 102, y, 90, 30, function()
    local hits = wada.mesh.discovered()
    if #hits == 0 then
      discline:set("discovered(): nothing yet - probe, then wait a few seconds")
      discline:color(C.sub); return
    end
    local h = hits[1]
    discline:set(string.format("discovered(): %d  first %s snr %.1f/%.1f %s",
      #hits, h.name or h.pubkey, h.snr, h.their_snr, h.direct and "direct" or (h.hops .. "h")))
    discline:color(C.good)
  end)
  y = y + 34
  ui.button("Beep", 6, y, 70, 30, function() sys.beep() end)
  ui.button("Input", 82, y, 90, 30, function()
    ui.input("Type anything", "hello", function(text)
      inputline:set("ui.input -> " .. (text and ("'" .. text .. "'") or "cancelled"))
      inputline:color(text and C.good or C.sub)
    end)
  end)
end

function app.on_input(ev)
  if ev.type == "key" and keyline then
    keyline:set("keys: got '" .. tostring(ev.key) .. "'")
    keyline:color(C.good)
  end
end

-- Proves the kind field and that DMs/rooms reach an app at all, not just channels.
function app.on_message(m)
  if not msgline then return end
  msgline:set("on_message: kind=" .. tostring(m.kind) .. " from=" .. tostring(m.sender) ..
              " ch=" .. tostring(m.channel) .. " text=" .. tostring(m.text):sub(1, 20))
  msgline:color(C.good)
end

return app
)WADALUA";
static const char kLuaSrc_wardrive[] = R"WADALUA(-- Wardrive v1.2 — LoRa coverage survey with live signal map.
--
-- Two views, tap the tab bar to switch:
--   MAP   — full-screen track coloured by best SNR. Green ≥0 dB, amber ≥-10,
--            red <-10. Current position shown as a dot.
--   NODES — node table sorted by best SNR with per-node SNR asymmetry.
--            ↓ = they heard us (their_snr), ↑ = we heard them (best SNR).
--
-- Each view rebuilds via ui.clear() on switch; stale handles become no-ops
-- (generation-tagged by the SDK). Map is closed before clear to release it.
--
-- CSV columns: epoch,lat_e6,lon_e6,alt_m,pubkey,name,type,rssi,snr,their_snr,hops
local ui, sys, mesh, fs, timer = wada.ui, wada.sys, wada.mesh, wada.fs, wada.timer
local C = ui.colors
local app = {}

-- ── constants ────────────────────────────────────────────────────────────────
local SWEEP_MS   = 20000   -- ≥15 s probe floor enforced by firmware
local HARVEST_MS = 4000    -- replies arrive over ~4 s after a probe
local TYPE = { [1]="chat", [2]="rep", [3]="room", [4]="sensor" }
local SNR_GOOD, SNR_OK = 0, -10   -- dB thresholds: good / marginal / bad

-- ── persistent survey state (survives view switches) ─────────────────────────
local run, running = "wd", false
local samples, sweeps, node_count = 0, 0, 0
local last_err = nil
local phase, phase_at = "idle", 0
local nodes   = {}   -- pubkey → { name, type, best, worst, their_snr, rssi, seen }
local pending = {}   -- write queue (fs allows 1 write/s)
local wrote_header = false
local track = {}     -- { lat, lon, snr } breadcrumb for the map

-- ── per-view UI handles (rebuilt on every switch) ────────────────────────────
local MAP_VIEW, NODE_VIEW = 1, 2
local cur_view = MAP_VIEW
local W, H = 0, 0

local map_obj   = nil   -- wada.map handle, nil when in node view
local node_list = nil   -- wada.list handle, nil when in map view
local status_lbl = nil
local gps_lbl    = nil
local start_btn  = nil

-- ── helpers ──────────────────────────────────────────────────────────────────
local function default_run_name()
  local dt = sys.datetime and sys.datetime()
  if dt then
    return string.format("wd_%04d%02d%02d_%02d%02d%02d",
      dt.year, dt.month, dt.day, dt.hour, dt.min, dt.sec)
  end
  local ep = sys.epoch and sys.epoch()
  if ep then return string.format("wd_%d", ep) end
  return "wd"
end

local function logname() return run .. ".csv" end

local function utf8_trunc(text, max_bytes)
  local offset, last, len = 1, 0, #text
  while offset <= len and offset <= max_bytes do
    local b = text:byte(offset)
    local w = (b <= 0x7F and 1) or (b >= 0xC2 and b <= 0xDF and 2)
           or (b >= 0xE0 and b <= 0xEF and 3) or (b >= 0xF0 and b <= 0xF4 and 4) or 0
    if w == 0 or offset + w - 1 > len or offset + w - 1 > max_bytes then break end
    local ok = true
    for i = 2, w do
      local c = text:byte(offset + i - 1)
      if c < 0x80 or c > 0xBF then ok = false; break end
    end
    local b2 = w > 1 and text:byte(offset + 1) or 0
    if (b == 0xE0 and b2 < 0xA0) or (b == 0xED and b2 > 0x9F) or
       (b == 0xF0 and b2 < 0x90) or (b == 0xF4 and b2 > 0x8F) then ok = false end
    if not ok then break end
    last = offset + w - 1; offset = last + 1
  end
  return text:sub(1, last)
end

local function snr_color(snr)
  if     snr >= SNR_GOOD then return C.good
  elseif snr >= SNR_OK   then return 0xC8A030
  else                        return C.bad end
end

-- ── CSV write queue ──────────────────────────────────────────────────────────
local HEADER = "epoch,lat_e6,lon_e6,alt_m,pubkey,name,type,rssi,snr,their_snr,hops"

local function flush()
  if #pending == 0 then return end
  local chunk = table.concat(pending, "\n") .. "\n"
  if not wrote_header then chunk = HEADER .. "\n" .. chunk end
  if fs.append(logname(), chunk) then pending, wrote_header = {}, true end
end

local function record(fix, hit)
  local key = hit.pubkey
  local n = nodes[key]
  if not n then
    n = { name = hit.name or key:sub(1,8), type = hit.type,
          best = hit.snr, worst = hit.snr,
          their_snr = hit.their_snr, rssi = hit.rssi, seen = 0 }
    nodes[key] = n
    node_count = node_count + 1
  else
    if hit.snr > n.best  then n.best  = hit.snr end
    if hit.snr < n.worst then n.worst = hit.snr end
    n.their_snr = hit.their_snr
    n.rssi      = hit.rssi
    if hit.name then n.name = hit.name end
  end
  n.seen = n.seen + 1
  samples = samples + 1
  pending[#pending + 1] = string.format("%d,%d,%d,%d,%s,%s,%d,%d,%.2f,%.2f,%d",
    fix.time or sys.epoch(), fix.lat_e6, fix.lon_e6, fix.alt_m or 0,
    key, (hit.name or ""):gsub(",", " "), hit.type,
    hit.rssi, hit.snr, hit.their_snr, hit.hops)
end

-- ── probe / harvest ──────────────────────────────────────────────────────────
local function do_sweep()
  local ok, err = mesh.discover()
  if not ok then last_err = err; return false end
  last_err = nil; sweeps = sweeps + 1; return true
end

local function do_harvest()
  local fix = sys.gps()
  if not fix then mesh.discover_clear(); return end
  local best_snr = nil
  for _, hit in ipairs(mesh.discovered()) do
    record(fix, hit)
    if not best_snr or hit.snr > best_snr then best_snr = hit.snr end
  end
  mesh.discover_clear()
  if fix.lat_e6 ~= 0 or fix.lon_e6 ~= 0 then
    track[#track + 1] = { lat = fix.lat_e6 / 1e6, lon = fix.lon_e6 / 1e6, snr = best_snr }
  end
end

-- ── draw helpers (called from on_tick; handles may be nil if wrong view) ─────
local function redraw_map()
  if not map_obj then return end
  map_obj:clear()
  local fix = sys.gps()
  if fix and (fix.lat_e6 ~= 0 or fix.lon_e6 ~= 0) then
    map_obj:center(fix.lat_e6 / 1e6, fix.lon_e6 / 1e6)
  end
  for i = 2, #track do
    local a, b = track[i-1], track[i]
    map_obj:line(a.lat, a.lon, b.lat, b.lon, b.snr and snr_color(b.snr) or 0x444C54, 3)
  end
  if fix and (fix.lat_e6 ~= 0 or fix.lon_e6 ~= 0) then
    map_obj:marker(fix.lat_e6 / 1e6, fix.lon_e6 / 1e6, C.accent, 6)
  end
  map_obj:redraw()
end

local function redraw_nodes()
  if not node_list then return end
  node_list:clear()
  local list = {}
  for key, n in pairs(nodes) do list[#list + 1] = { key = key, n = n } end
  table.sort(list, function(a, b) return a.n.best > b.n.best end)
  if #list == 0 then node_list:add("(no replies yet)", 0, C.sub); return end
  for _, e in ipairs(list) do
    local n = e.n
    local label = string.format("%-10s %-6s  \xe2\x86\x93%+5.1f  \xe2\x86\x91%+5.1f  \xc3\x97%d",
      utf8_trunc(n.name, 10), TYPE[n.type] or "?", n.their_snr, n.best, n.seen)
    node_list:add(label, 0, snr_color(n.best))
  end
end

local function redraw_status()
  if not status_lbl then return end
  local fix = sys.gps()
  if fix and (fix.lat_e6 ~= 0 or fix.lon_e6 ~= 0) then
    gps_lbl:set(string.format("%.5f %.5f  %dm  %dsat",
      fix.lat_e6 / 1e6, fix.lon_e6 / 1e6, fix.alt_m or 0, fix.sats or 0))
    gps_lbl:color(C.good)
  else
    gps_lbl:set("no GPS fix \xe2\x80\x94 samples discarded until locked")
    gps_lbl:color(C.bad)
  end
  local state_str
  if not running then
    state_str = "stopped"
  elseif phase == "probe" then
    state_str = "listening\xe2\x80\xa6"
  else
    local rem = math.max(0, SWEEP_MS - (sys.millis() - phase_at))
    state_str = string.format("next probe %ds", math.ceil(rem / 1000))
  end
  status_lbl:set(string.format("%s  \xe2\x80\xa2  %d sweeps  %d nodes%s",
    state_str, sweeps, node_count,
    last_err and ("  [\xe2\x9a\xa0 " .. last_err .. "]") or ""))
  status_lbl:color(last_err and C.bad or (running and C.accent or C.sub))
end

-- ── view builder (called on open and on every tab switch) ────────────────────
local function build_view(v)
  cur_view = v

  -- release map before wiping widgets (one-at-a-time SDK limit)
  if map_obj then map_obj:close(); map_obj = nil end
  ui.clear()

  -- null out handles — generation bump made them stale anyway
  node_list, status_lbl, gps_lbl, start_btn = nil, nil, nil, nil

  local LH = ui.text_h(12)
  local y = 2

  gps_lbl    = ui.label("", 4, y, 12, C.sub);    gps_lbl:width(W - 8);    y = y + LH + 2
  status_lbl = ui.label("", 4, y, 12, C.accent); status_lbl:width(W - 8); y = y + LH + 3

  -- control row
  local bw = math.min(80, (W - 16) // 3)
  start_btn = ui.button("Start", 4, y, bw, 26, function()
    running = not running
    if running then phase, phase_at = "idle", 0 end
    start_btn:set(running and "Stop" or "Start")
    sys.toast(running and "Survey running" or "Survey stopped", 1000)
  end)
  if running then start_btn:set("Stop") end
  ui.button("Name", 8 + bw, y, bw, 26, function()
    ui.input("Name this run", run, function(text)
      if text and text ~= "" then
        run = text:gsub("[^%w%-_]", "_")
        wrote_header = false
        sys.toast("Logging to " .. logname(), 1500)
      end
    end)
  end)
  ui.button("Reset", 12 + bw * 2, y, bw, 26, function()
    nodes, samples, sweeps, pending, node_count = {}, 0, 0, {}, 0
    track = {}; mesh.discover_clear()
    fs.remove(logname()); wrote_header = false
    run = default_run_name()
    sys.toast("Cleared \xe2\x80\x94 new run: " .. run, 1500)
    redraw_nodes(); redraw_map()
  end)
  y = y + 30

  -- tab bar
  local has_map = sys.caps().map
  if has_map then
    local tw = (W - 12) // 2
    local mb = ui.button("Map",   4,      y, tw, 24, function() build_view(MAP_VIEW)  end)
    local nb = ui.button("Nodes", 8 + tw, y, tw, 24, function() build_view(NODE_VIEW) end)
    mb:color(v == MAP_VIEW  and C.accent or C.sub)
    nb:color(v == NODE_VIEW and C.accent or C.sub)
    y = y + 28
  end

  local content_h = H - y - 2

  if v == MAP_VIEW and has_map then
    map_obj = wada.map.view(4, y, W - 8, content_h)
    local fix = sys.gps()
    if fix and (fix.lat_e6 ~= 0 or fix.lon_e6 ~= 0) then
      map_obj:center(fix.lat_e6 / 1e6, fix.lon_e6 / 1e6, 13)
    else
      map_obj:zoom(13)
    end
    redraw_map()
  else
    -- NODE_VIEW, or MAP_VIEW on a board without map support
    node_list = ui.list(4, y, W - 8, content_h, function(_idx) end)
    redraw_nodes()
  end

  redraw_status()
end

-- ── app callbacks ─────────────────────────────────────────────────────────────
function app.on_open(w, h)
  if not sys.caps().discover then
    ui.label("This board does not support discovery probes.", 6, 8, 12, C.bad)
    return
  end
  W, H = w, h
  run = default_run_name()
  ui.scroll(false)
  build_view(MAP_VIEW)
  timer.every(1000)
end

function app.on_tick()
  if running then
    local now = sys.millis()
    if phase == "idle" or (phase == "wait" and now - phase_at >= SWEEP_MS) then
      phase, phase_at = do_sweep() and "probe" or "wait", now
    elseif phase == "probe" and now - phase_at >= HARVEST_MS then
      do_harvest()
      phase = "wait"
      redraw_map()
      redraw_nodes()
    end
  end
  flush()
  redraw_status()
  -- keep position dot moving between sweeps
  if map_obj then
    local fix = sys.gps()
    if fix and (fix.lat_e6 ~= 0 or fix.lon_e6 ~= 0) then
      map_obj:center(fix.lat_e6 / 1e6, fix.lon_e6 / 1e6)
      map_obj:redraw()
    end
  end
end

function app.on_close()
  flush()
  if map_obj then map_obj:close() end
end

return app
)WADALUA";
static const char kLuaSrc_nearby[] = R"WADALUA(-- Nearby (Lua) — contacts on a real map, with distance and bearing, and a live
-- packet counter.
--
-- Reference app for the four things the SDK gained alongside it: wada.map (the
-- firmware's own tiles inside an app page), wada.ui.list (scrollable selectable
-- rows), app.on_packet (each frame delivered once instead of polled), and
-- wada.geo (great-circle maths in C rather than in your instruction budget).
local ui, sys, mesh, geo, timer = wada.ui, wada.sys, wada.mesh, wada.geo, wada.timer
local C = ui.colors
local app = {}

local map, list, hdr, detail = nil, nil, nil, nil
local pts, sel = {}, 0
local pkt_count, pkt_adverts = 0, 0
local W, H

local function here()
  local fix = sys.gps()
  if fix then return fix.lat, fix.lon, true end
  local me = mesh.self()
  -- self() is the last known position, which may be old. Say which one is in
  -- use rather than presenting a stale fix as a live one.
  if me.lat ~= 0 or me.lon ~= 0 then return me.lat, me.lon, false end
  return nil
end

local function fmt_dist(m)
  if m < 1000 then return string.format("%.0f m", m) end
  return string.format("%.1f km", m / 1000)
end

local function rebuild()
  local lat, lon, live = here()
  pts, sel = {}, 0
  for _, c in ipairs(mesh.contacts()) do
    if c.lat ~= 0 or c.lon ~= 0 then
      local e = { name = c.name, lat = c.lat, lon = c.lon, type = c.type, pubkey = c.pubkey }
      if lat then
        e.dist = geo.distance(lat, lon, c.lat, c.lon)
        e.brg  = geo.bearing(lat, lon, c.lat, c.lon)
      end
      pts[#pts + 1] = e
    end
  end
  if lat then table.sort(pts, function(a, b) return (a.dist or 1e9) < (b.dist or 1e9) end) end

  list:clear()
  for i, e in ipairs(pts) do
    local label = e.dist
      and string.format("%-12s  %8s  %-2s", e.name:sub(1, 12), fmt_dist(e.dist), geo.cardinal(e.brg))
      or  e.name
    list:add(label, function() app.pick(i) end)
  end
  if #pts == 0 then list:add("no contacts have a position yet") end

  hdr:set(string.format("%d placed  |  %s  |  %d frames (%d adverts)",
    #pts, lat and (live and "GPS fix" or "last known position") or "no position", pkt_count, pkt_adverts))
  hdr:color(lat and C.accent or C.bad)

  if lat then app.draw(lat, lon) end
end

function app.draw(lat, lon)
  if not map then return end
  map:center(lat, lon)
  map:clear()
  if map:tiles() == 0 then
    -- An empty rectangle looks like open water. Say what it actually is.
    detail:set("no map tiles cached here at zoom " .. map:zoom())
    detail:color(C.sub)
  end
  for i, e in ipairs(pts) do
    map:line(lat, lon, e.lat, e.lon, i == sel and C.good or 0x2A3340, i == sel and 2 or 1)
  end
  for i, e in ipairs(pts) do
    map:marker(e.lat, e.lon, i == sel and C.good or C.accent, i == sel and 12 or 8)
  end
  map:marker(lat, lon, 0xE8A33D, 10)      -- us, last so it sits on top
end

function app.pick(i)
  sel = i
  list:select(i)
  local e = pts[i]
  if not e then return end
  local lat, lon = here()
  if e.dist then
    detail:set(string.format("%s  %s  %.0f deg (%s)  %s",
      e.name, fmt_dist(e.dist), e.brg, geo.cardinal(e.brg), e.pubkey))
  else
    detail:set(e.name .. "  " .. e.pubkey)
  end
  detail:color(C.text)
  if lat then app.draw(lat, lon) end
end

function app.on_open(w, h)
  W, H = w, h
  local LH = ui.text_h(12)
  hdr = ui.label("", 4, 4, 12, C.accent); hdr:width(w - 10)

  -- hdr and detail below are width-limited, which turns wrapping on, and both
  -- carry variable-length text (node names, a status phrase). Reserve two lines
  -- for each: a wrapped line would otherwise be drawn over by whatever follows.
  local map_h = math.floor(h * 0.45)
  local y = 4 + LH * 2 + 4
  if sys.caps().map then
    map = wada.map.view(4, y, w - 8, map_h)
  else
    ui.label("this board has no map support", 6, y + 10, 12, C.sub)
  end
  y = y + map_h + 4

  detail = ui.label("pick a contact", 4, y, 12, C.sub); detail:width(w - 10)
  y = y + LH * 2 + 4

  list = ui.list(4, y, w - 8, h - y - 4)

  rebuild()
  -- Two cadences, which is what wada.timer.after/every made possible: a slow
  -- rebuild (contacts and GPS move slowly) and no fast tick at all, because
  -- packets now arrive by callback instead of being polled for.
  timer.every(5000, rebuild)
end

-- One call per frame the radio received, in arrival order. Counting was simply
-- not possible against a polled 16-entry ring.
function app.on_packet(p)
  pkt_count = pkt_count + 1
  if p.pubkey then pkt_adverts = pkt_adverts + 1 end
end

function app.on_close()
  if map then map:close() end
end

return app
)WADALUA";

static const LuaBuiltinApp kLuaBuiltin[] = {
  { "monitor", "RF Monitor", "1.3", kLuaSrc_monitor },
  { "airtime", "Airtime", "1.4", kLuaSrc_airtime },
  { "sdktest", "SDK Test", "1.7", kLuaSrc_sdktest },
  { "wardrive", "Wardrive", "1.2", kLuaSrc_wardrive },
  { "nearby", "Nearby", "1.0", kLuaSrc_nearby },
};
static const int kLuaBuiltinCount = (int)(sizeof(kLuaBuiltin)/sizeof(kLuaBuiltin[0]));
