// Generated by scripts/build/gen-lua-builtin.py — DO NOT EDIT.
// Source: deploy/apps/ (the same .lua the Lua Store serves).
// Seeded built-ins: a downloaded <data>/apps/<id>.lua always wins.
#pragma once

struct LuaBuiltinApp { const char* id; const char* name; const char* ver; const char* src; };

static const char kLuaSrc_monitor[] = R"WADALUA(-- RF Monitor (Lua) — live RSSI/noise chart with a dBm axis, link-margin grade,
-- RX rate, radio parameters and the recently-heard feed. The page scrolls, so
-- the whole feed is reachable on short screens.
local ui, sys, mesh, timer = wada.ui, wada.sys, wada.mesh, wada.timer
local C = ui.colors
local app = {}

local RSSI_MIN, RSSI_MAX = -130, -20
local TYPE = { [1]="ADV", [2]="TXT", [3]="ACK", [4]="GRP", [5]="REQ", [6]="RSP", [7]="PTH", [8]="TRC" }
local TCOL = { [1]=0xA784E0, [2]=0x4F9DF7, [3]=0x53C06B, [4]=0x35C9C9, [5]=0xE8A33D, [6]=0xF2793C }

local W, narrow
local legend, chart, metrics, radio_lbl, feed_hdr, feed_rows = nil, nil, nil, nil, nil, {}
local peak, rx0, t0

local function fmt_ago(ms)
  local s = ms // 1000
  if s < 60 then return s .. "s" end
  if s < 3600 then return (s // 60) .. "m" end
  return (s // 3600) .. "h"
end

local function grade(m)
  if m >= 20 then return "excellent", C.good end
  if m >= 10 then return "good",      C.good end
  if m >= 5  then return "fair",      0xE8A33D end
  if m > 0   then return "weak",      C.bad end
  return "no margin", C.bad
end

local function refresh()
  local st = mesh.stats()
  if st.rssi > peak then peak = st.rssi end
  chart:push(1, math.floor(st.rssi))
  chart:push(2, math.floor(st.noise))

  local mg = st.rssi - st.noise
  local gtxt, gcol = grade(mg)
  local mins = math.max((sys.millis() - t0) / 60000, 1 / 60)

  legend:set(string.format("RSSI %.0f   noise %.0f   peak %.0f dBm", st.rssi, st.noise, peak))
  metrics:set(string.format("margin %.0f dB (%s)   RX ~%.0f/min", mg, gtxt, (st.rx_pkts - rx0) / mins))
  metrics:color(gcol)
  radio_lbl:set(string.format("%.3f MHz  SF%d  BW %.0f   %d rx / %d err / %d drop   duty %d%%",
                              st.freq, st.sf, st.bw, st.rx_pkts, st.rx_err, st.rx_dropped, st.duty_pct))

  local log = mesh.rx_log()
  for i = 1, #feed_rows do
    local r = log[i]
    if r then
      local nm = TYPE[r.type] or ("t" .. r.type)
      if narrow then
        feed_rows[i]:set(string.format("%-4s %-3s %4d %5.1f %s", fmt_ago(r.ago_ms), nm, r.rssi, r.snr,
                                       r.hops == 0 and "dir" or (r.hops .. "h")))
      else
        feed_rows[i]:set(string.format("%-5s %-3s  %4d dBm  %5.1f dB  %s", fmt_ago(r.ago_ms), nm, r.rssi, r.snr,
                                       r.hops == 0 and "direct" or (r.hops .. (r.hops == 1 and " hop" or " hops"))))
      end
      feed_rows[i]:color(TCOL[r.type] or C.text)
    else
      feed_rows[i]:set(i == 1 and #log == 0 and "listening - nothing heard yet" or "")
      feed_rows[i]:color(C.sub)
    end
  end
end

function app.on_open(w, h)
  W, narrow = w, w < 280
  ui.scroll(true)                      -- the feed runs past the screen; let it scroll
  local LH12 = ui.text_h(12)           -- real line heights, no guessing
  local st = mesh.stats()
  rx0, t0, peak = st.rx_pkts, sys.millis(), st.rssi

  local y = 4
  legend = ui.label("", 4, y, 12, C.accent); legend:width(w - 10); y = y + LH12 + 4

  local AX, ch_h = 38, narrow and 62 or 76
  chart = ui.chart(w - AX - 8, ch_h, 72, C.accent, C.sub)
  chart:pos(AX, y)
  chart:range(RSSI_MIN, RSSI_MAX)
  chart:axis(3, AX)
  y = y + ch_h + 6

  metrics = ui.label("", 4, y, 12, C.text); metrics:width(w - 10)
  y = y + LH12 * (narrow and 2 or 1) + 3
  radio_lbl = ui.label("", 4, y, 12, C.sub); radio_lbl:width(w - 10)
  y = y + LH12 * (narrow and 3 or 2) + 5

  feed_hdr = ui.label(narrow and "recently heard" or "recently heard (newest first)", 4, y, 12, C.sub)
  feed_hdr:width(w - 10)
  y = y + LH12 + 3
  for i = 1, 16 do                     -- scrolling means we can show the whole ring
    feed_rows[i] = ui.label("", 4, y, 12, C.text)
    feed_rows[i]:width(w - 10)
    y = y + LH12 + 2
  end

  refresh()
  timer.every(1000)
end

function app.on_tick(dt) refresh() end

return app
)WADALUA";
static const char kLuaSrc_airtime[] = R"WADALUA(-- Airtime (Lua) — channel utilization over time: live + average bars with a %
-- axis, rx/tx air split, duty ceiling, tx budget and packet counters.
local ui, sys, mesh, timer = wada.ui, wada.sys, wada.mesh, wada.timer
-- Translate through the device's language table (wada.sys.tr, added for #257).
-- Older firmware has no sys.tr, so fall back to the English string rather than error.
local tr = sys.tr or function(x) return x end
local C = ui.colors
local app = {}

local W, narrow
local head, sub, legend, detail, chart
local base, t0, last
local peak_pct = 0

local function restart_window()
  local st = mesh.stats()
  base = { rx = st.rx_air_s, tx = st.tx_air_s }
  t0 = sys.millis()
  last = { ms = t0, rx = st.rx_air_s, tx = st.tx_air_s }
  peak_pct = 0
  chart:fill(1, 0)
  chart:fill(2, 0)
  head:set(tr("sampling..."))
  head:color(C.accent)
  sys.toast(tr("window restarted"), 900)
end

local function refresh()
  local st = mesh.stats()
  local now = sys.millis()
  local wall = (now - t0) / 1000
  if wall < 0.5 then return end

  local rx_air, tx_air = st.rx_air_s - base.rx, st.tx_air_s - base.tx
  local avg = math.min(100, (rx_air + tx_air) * 100 / wall)

  local dw = (now - last.ms) / 1000
  local live = 0
  if dw > 0 then
    live = math.min(100, ((st.rx_air_s - last.rx) + (st.tx_air_s - last.tx)) * 100 / dw)
  end
  last = { ms = now, rx = st.rx_air_s, tx = st.tx_air_s }
  if live > peak_pct then peak_pct = live end

  chart:push(1, math.floor(live))
  chart:push(2, math.floor(avg))

  head:set(string.format(tr("channel busy %.1f%%"), live))
  head:color(live > 50 and C.bad or live > 20 and 0xE8A33D or C.good)
  sub:set(string.format(tr("avg %.1f%%   peak %.1f%%   over %ds"), avg, peak_pct, math.floor(wall)))
  if narrow then
    detail:set(string.format("air rx %ds / tx %ds\nduty %d%%   budget %dms\ntx %d  rx %d  err %d",
      rx_air, tx_air, st.duty_pct, st.tx_budget_ms, st.tx_pkts, st.rx_pkts, st.rx_err))
  else
    detail:set(string.format("air rx %ds / tx %ds   duty %d%%   budget %dms\ntx %d   rx %d   err %d   drop %d   SF%d",
      rx_air, tx_air, st.duty_pct, st.tx_budget_ms, st.tx_pkts, st.rx_pkts, st.rx_err, st.rx_dropped, st.sf))
  end
end

function app.on_open(w, h)
  W, narrow = w, w < 280
  local LH12, LH16 = ui.text_h(12), ui.text_h(16)

  local y = 2
  head = ui.label(tr("sampling..."), 4, y, 16, C.accent); head:width(w - 86)
  ui.button(tr("Reset"), w - 76, y, 70, 30, function() restart_window() end)   -- top-right
  y = y + LH16 + 4
  sub = ui.label("", 4, y, 12, C.sub); sub:width(w - 10)
  y = y + LH12 + 5

  local AX = 34
  local det_lines = narrow and 3 or 2
  local ch_h = h - y - (det_lines * LH12) - LH12 - 14
  if ch_h < 48 then ch_h = 48 end
  if ch_h > 110 then ch_h = 110 end
  chart = ui.chart(w - AX - 8, ch_h, 60, C.accent, 0x4F9DF7, true)
  chart:pos(AX, y)
  chart:range(0, 100)
  chart:axis(3, AX)
  y = y + ch_h + 4

  legend = ui.label(tr("teal = now   blue = average"), 4, y, 12, C.sub); legend:width(w - 10)
  y = y + LH12 + 2
  detail = ui.label("", 4, y, 12, C.text); detail:width(w - 10)

  local st = mesh.stats()
  base = { rx = st.rx_air_s, tx = st.tx_air_s }
  t0 = sys.millis()
  last = { ms = t0, rx = st.rx_air_s, tx = st.tx_air_s }
  timer.every(1000)
end

function app.on_tick(dt) refresh() end

return app
)WADALUA";
static const char kLuaSrc_sdktest[] = R"WADALUA(-- SDK self-test. Exercises the extended SDK so the results can be read off the
-- screen instead of inferred from a build log. Published to the store as a
-- developer/bench tool.
--
-- 1.2 adds wada.crypto (checked against published RFC vectors, so a PASS here is
-- real evidence and not just "it returned something"), wada.mesh.channels, and
-- wada.mesh.send_dm.
-- 1.3 adds the discovery surface (wada.mesh.discover / discovered), packet
-- identity in rx_log, exact micro-degree coordinates, wada.ui.input and the
-- windowed wada.fs.read.
-- 1.6 adds wada.sd.list: capability reporting, traversal rejection, root
-- metadata, and a nested directory listing when the card contains one.
-- 1.7 adds storage-neutral wada.audio capability and API-shape checks. Playback
-- stays manual so opening the bench test never emits sound unexpectedly.
-- 1.5 uses wada.ui.text_lines() to measure instead of estimating, where the
-- firmware has it. That call was added because of the 1.3 bug below: an app
-- could ask how tall a line is but not how wide, so laying out rows meant
-- guessing whether text would wrap. Falls back to the 1.4 estimate on older
-- firmware, so it still lays out correctly there.
-- 1.4 fixes rows drawing on top of one another. label:width() turns wrapping
-- on, so any line wider than the screen became two lines while the caller still
-- advanced by one, and the next row landed on top. Reported with a photo of the
-- channels line sitting across the contacts line. row() now owns the cursor and
-- advances by the height the text actually needs.
local ui, sys, store, timer = wada.ui, wada.sys, wada.store, wada.timer
local C = ui.colors

local app = {}
local rows, keyline, sendline, dmline, msgline = {}, nil, nil, nil, nil
local discline, inputline = nil, nil
local W = 300

-- row() owns the vertical cursor. Every caller used to pass a y and then add a
-- hand-picked constant, which is only correct while the text fits on one line.
-- An app cannot measure rendered text, so the wrapped line count is estimated
-- from a deliberately pessimistic character width: over-estimating costs a
-- little whitespace, under-estimating overlaps the next row.
local LH, GAP = 14, 3
local cy = 4
local function row(text, color, extra_gap)
  local l = ui.label(text, 6, cy, 12, color or C.text)
  l:width(W - 12)
  rows[#rows + 1] = l
  local n
  if ui.text_lines then
    n = ui.text_lines(tostring(text), W - 12, 12)     -- measured: exact
  else
    local cpl = math.max(16, (W - 12) // 7)           -- older firmware: estimate
    n = 0
    for seg in (tostring(text) .. "\n"):gmatch("(.-)\n") do
      n = n + math.max(1, math.ceil(#seg / cpl))
    end
  end
  cy = cy + math.max(1, n or 1) * LH + GAP + (extra_gap or 0)
  return l
end
local function yn(v) return v and "yes" or "NO" end

function app.on_open(w, h)
  W = w or 300
  ui.scroll(true)
  cy = 4
  local y

  local c = sys.caps()
  row("caps: sdk_ext=" .. yn(c.sdk_ext) .. "  kbd=" .. yn(c.keyboard) ..
         "  touch=" .. yn(c.touch) .. "  sd=" .. yn(c.sd), C.accent)
    row("caps: sd_list=" .. yn(c.sd_list) .. "  discover=" .. yn(c.discover) ..
      "  input=" .. yn(c.input) ..
         "  rx_identity=" .. yn(c.rx_identity), C.accent)
    row("caps: audio=" .. yn(c.audio) .. "  wav=" .. yn(c.audio_wav) ..
           "  mp3=" .. yn(c.audio_mp3) .. "  audio_sd=" .. yn(c.audio_sd), C.accent)
    if c.audio then
      local api_ok = wada.audio and type(wada.audio.play) == "function" and
                     type(wada.audio.pause) == "function" and
                     type(wada.audio.resume) == "function" and
                     type(wada.audio.stop) == "function" and
                     type(wada.audio.status) == "function"
      local status = api_ok and wada.audio.status() or nil
      api_ok = api_ok and type(status) == "table" and type(status.state) == "string"
      row("wada.audio API: " .. (api_ok and ("PASS (" .. status.state .. ")") or "FAIL"),
          api_ok and C.good or C.bad)
    else
      row("wada.audio: unavailable on this board", C.sub)
    end
  row("layout: " .. (ui.text_lines and "measured (ui.text_lines)" or "estimated (older firmware)"),
      ui.text_lines and C.good or C.sub)
  -- crypto: published test vectors, so this is checkable rather than merely alive
  if wada.crypto then
    local hex = wada.crypto.hex
    local k20 = string.rep(string.char(0x0b), 20)
    local checks = {
      { "sha256('abc')", hex(wada.crypto.sha256("abc")),
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad" },
      { "sha1('abc')", hex(wada.crypto.sha1("abc")),
        "a9993e364706816aba3e25717850c26c9cd0d89d" },
      { "hmac_sha1 RFC2202#1", hex(wada.crypto.hmac_sha1(k20, "Hi There")),
        "b617318655057264e28bc0b6fb378c8ef146be00" },
      { "hmac_sha256 RFC4231#1", hex(wada.crypto.hmac_sha256(k20, "Hi There")),
        "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7" },
    }
    local allok = true
    for _, t in ipairs(checks) do
      local ok = (t[2] == t[3])
      if not ok then allok = false end
      row("crypto " .. t[1] .. ": " .. (ok and "PASS" or ("FAIL got " .. tostring(t[2]):sub(1, 16))),
          ok and C.good or C.bad)
    end
    -- The point of having it in C: this loop would blow the instruction budget in Lua.
    local t0 = sys.millis()
    for _ = 1, 200 do wada.crypto.hmac_sha1(k20, "Hi There") end
    row(string.format("crypto: 200 x hmac_sha1 in %d ms%s", sys.millis() - t0,
        allok and "" or "  (VECTORS FAILED)"), allok and C.good or C.bad)
  else
    row("wada.crypto: MISSING", C.bad)
  end

  -- channel discovery
  local chans = wada.mesh.channels and wada.mesh.channels() or nil
  if chans then
    local names = table.concat(chans, ", ")
    row("channels(): " .. #chans .. "  " .. names:sub(1, 60), C.text)
  else
    row("wada.mesh.channels: MISSING", C.bad)
  end

  if not c.sdk_ext then
    row("extended SDK is OFF on this board - stopping here.", C.sub)
    return
  end

  -- contacts, so send_dm has a target to name. 1.3 also checks the pubkey field.
  local cts = wada.mesh.contacts()
  local first = cts[1] and cts[1].name or nil
  row("contacts: " .. #cts .. (first and ("  first=" .. first) or ""), C.text)
  if cts[1] then
    local pk = cts[1].pubkey
    row("contacts[1].pubkey: " .. tostring(pk) ..
           (type(pk) == "string" and #pk == 8 and "  PASS" or "  FAIL"),
        (type(pk) == "string" and #pk == 8) and C.good or C.bad)
  end

  local me = wada.mesh.self()
  row("self: " .. tostring(me.name) .. "  pubkey=" .. tostring(me.pubkey), C.text)
  -- Exact coordinates. Lua's floats here are 32-bit, so an app that logs a track
  -- must use the _e6 integers; this proves they are present and consistent.
  local fix = sys.gps()
  if fix then
    local drift = math.abs(fix.lat_e6 / 1e6 - fix.lat)
    row(string.format("gps: %d,%d e6  alt %dm  %d sats  drift %.6f  %s",
        fix.lat_e6, fix.lon_e6, fix.alt_m or 0, fix.sats, drift,
        drift < 0.001 and "PASS" or "FAIL"), drift < 0.001 and C.good or C.bad)
  else
    row("gps: no fix (normal indoors)", C.sub)
  end

  -- rx_log identity: adverts carry a real public key, addressed frames carry
  -- one-byte hashes, everything else carries nothing. All three are correct.
  local log = wada.mesh.rx_log()
  local withpk, withsrc = 0, 0
  for _, r in ipairs(log) do
    if r.pubkey then withpk = withpk + 1 end
    if r.src then withsrc = withsrc + 1 end
  end
  row(string.format("rx_log: %d frames, %d with a pubkey (adverts), %d with src/dst",
      #log, withpk, withsrc), #log > 0 and C.text or C.sub)
  -- fs: windowed read. Writes once (the 1/sec limit means one write per open).
  if wada.fs then
    local probe = "0123456789abcdef"
    wada.fs.write("sdktest.bin", probe)
    local part, total = wada.fs.read("sdktest.bin", 4, 4)
    local ok = (part == "4567" and total == #probe)
    row("fs.read(name,4,4): " .. tostring(part) .. " total=" .. tostring(total) ..
           (ok and "  PASS" or "  FAIL"), ok and C.good or C.bad)
  end

  -- Physical SD listing is read-only and independently feature-detected. A
  -- supported board with no inserted card is a normal bench state, not a test
  -- failure; API shape and path rejection can still be checked separately.
  if c.sd_list then
    if not wada.sd or not wada.sd.list then
      row("wada.sd.list: MISSING despite caps", C.bad)
    else
      local guard_ok, guard_failure = true, nil
      local bad_paths = { "/..", "/.", "/a/../b", "/a//b", "/a/", "relative", "/a\\b" }
      for _, path in ipairs(bad_paths) do
        local rejected, baderr = wada.sd.list(path)
        if rejected ~= nil or baderr ~= "bad path" then
          guard_ok = false
          guard_failure = path .. " -> " .. tostring(baderr)
          break
        end
      end
      row("sd traversal guard: " .. (guard_ok and "PASS" or ("FAIL " .. guard_failure)),
          guard_ok and C.good or C.bad)

      local entries, err = wada.sd.list("/")
      if not entries then
        local note = err == "busy" and " (retry later)" or " (no readable card)"
        row("sd.list('/'): " .. tostring(err) .. note, C.sub)
      else
        local metadata_ok, first_dir = true, nil
        for _, entry in ipairs(entries) do
          if type(entry.name) ~= "string" or
             (entry.type ~= "file" and entry.type ~= "dir") or
             type(entry.size) ~= "number" or type(entry.mtime) ~= "number" then
            metadata_ok = false
          end
          if not first_dir and entry.type == "dir" then first_dir = entry.name end
        end
        row("sd.list('/'): " .. #entries .. " entries, metadata " ..
               (metadata_ok and "PASS" or "FAIL") ..
               (entries.truncated and " (truncated)" or ""),
            metadata_ok and C.good or C.bad)
        if first_dir then
          local nested, nested_err = wada.sd.list("/" .. first_dir)
          row("sd.list('/" .. first_dir .. "'): " ..
                 (nested and (#nested .. " entries PASS") or ("FAIL " .. tostring(nested_err))),
              nested and C.good or C.bad)
        else
          row("sd nested listing: no directory on card to test", C.sub)
        end
      end
    end
  else
    row("wada.sd.list: unavailable on this board", C.sub)
  end

  sendline = row("mesh.send: not tried yet", C.sub)
  dmline   = row("mesh.send_dm: not tried yet", C.sub)
  msgline  = row("on_message: waiting (needs the read permissions)", C.sub)
  y = cy + 4
  ui.button("Send to Public", 6, y, 120, 30, function()
    local ok, err = wada.mesh.send("Public", "wadamesh SDK self-test")
    sendline:set("mesh.send: " .. tostring(ok) .. "  " .. tostring(err))
    sendline:color(ok and C.good or C.bad)
  end)
  ui.button("DM first contact", 132, y, 130, 30, function()
    if not first then dmline:set("mesh.send_dm: no contacts to target"); dmline:color(C.bad); return end
    local ok, err = wada.mesh.send_dm(first, "wadamesh SDK self-test (DM)")
    dmline:set("mesh.send_dm -> " .. first .. ": " .. tostring(ok) .. "  " .. tostring(err))
    dmline:color(ok and C.good or C.bad)
  end)
  cy = y + 38
  discline  = row("mesh.discover: not tried yet", C.sub)
  inputline = row("ui.input: not tried yet", C.sub)
  -- Probing TRANSMITS and makes every neighbour reply, so it is a button, not
  -- something this app does on open.
  y = cy + 4
  ui.button("Probe", 6, y, 90, 30, function()
    local tag, err = wada.mesh.discover()
    if not tag then
      discline:set("mesh.discover: " .. tostring(err)); discline:color(C.bad); return
    end
    discline:set("mesh.discover: sent, waiting for replies..."); discline:color(C.text)
  end)
  ui.button("Results", 102, y, 90, 30, function()
    local hits = wada.mesh.discovered()
    if #hits == 0 then
      discline:set("discovered(): nothing yet - probe, then wait a few seconds")
      discline:color(C.sub); return
    end
    local h = hits[1]
    discline:set(string.format("discovered(): %d  first %s snr %.1f/%.1f %s",
      #hits, h.name or h.pubkey, h.snr, h.their_snr, h.direct and "direct" or (h.hops .. "h")))
    discline:color(C.good)
  end)
  y = y + 34
  ui.button("Beep", 6, y, 70, 30, function() sys.beep() end)
  ui.button("Input", 82, y, 90, 30, function()
    ui.input("Type anything", "hello", function(text)
      inputline:set("ui.input -> " .. (text and ("'" .. text .. "'") or "cancelled"))
      inputline:color(text and C.good or C.sub)
    end)
  end)
end

function app.on_input(ev)
  if ev.type == "key" and keyline then
    keyline:set("keys: got '" .. tostring(ev.key) .. "'")
    keyline:color(C.good)
  end
end

-- Proves the kind field and that DMs/rooms reach an app at all, not just channels.
function app.on_message(m)
  if not msgline then return end
  msgline:set("on_message: kind=" .. tostring(m.kind) .. " from=" .. tostring(m.sender) ..
              " ch=" .. tostring(m.channel) .. " text=" .. tostring(m.text):sub(1, 20))
  msgline:color(C.good)
end

return app
)WADALUA";
static const char kLuaSrc_nearby[] = R"WADALUA(-- Nearby (Lua) — contacts on a real map, with distance and bearing, and a live
-- packet counter.
--
-- Reference app for the four things the SDK gained alongside it: wada.map (the
-- firmware's own tiles inside an app page), wada.ui.list (scrollable selectable
-- rows), app.on_packet (each frame delivered once instead of polled), and
-- wada.geo (great-circle maths in C rather than in your instruction budget).
local ui, sys, mesh, geo, timer = wada.ui, wada.sys, wada.mesh, wada.geo, wada.timer
local C = ui.colors
local app = {}

local map, list, hdr, detail = nil, nil, nil, nil
local pts, sel = {}, 0
local pkt_count, pkt_adverts = 0, 0
local W, H

local function here()
  local fix = sys.gps()
  if fix then return fix.lat, fix.lon, true end
  local me = mesh.self()
  -- self() is the last known position, which may be old. Say which one is in
  -- use rather than presenting a stale fix as a live one.
  if me.lat ~= 0 or me.lon ~= 0 then return me.lat, me.lon, false end
  return nil
end

local function fmt_dist(m)
  if m < 1000 then return string.format("%.0f m", m) end
  return string.format("%.1f km", m / 1000)
end

local function rebuild()
  local lat, lon, live = here()
  pts, sel = {}, 0
  for _, c in ipairs(mesh.contacts()) do
    if c.lat ~= 0 or c.lon ~= 0 then
      local e = { name = c.name, lat = c.lat, lon = c.lon, type = c.type, pubkey = c.pubkey }
      if lat then
        e.dist = geo.distance(lat, lon, c.lat, c.lon)
        e.brg  = geo.bearing(lat, lon, c.lat, c.lon)
      end
      pts[#pts + 1] = e
    end
  end
  if lat then table.sort(pts, function(a, b) return (a.dist or 1e9) < (b.dist or 1e9) end) end

  list:clear()
  for i, e in ipairs(pts) do
    local label = e.dist
      and string.format("%-12s  %8s  %-2s", e.name:sub(1, 12), fmt_dist(e.dist), geo.cardinal(e.brg))
      or  e.name
    list:add(label, function() app.pick(i) end)
  end
  if #pts == 0 then list:add("no contacts have a position yet") end

  hdr:set(string.format("%d placed  |  %s  |  %d frames (%d adverts)",
    #pts, lat and (live and "GPS fix" or "last known position") or "no position", pkt_count, pkt_adverts))
  hdr:color(lat and C.accent or C.bad)

  if lat then app.draw(lat, lon) end
end

function app.draw(lat, lon)
  if not map then return end
  map:center(lat, lon)
  map:clear()
  if map:tiles() == 0 then
    -- An empty rectangle looks like open water. Say what it actually is.
    detail:set("no map tiles cached here at zoom " .. map:zoom())
    detail:color(C.sub)
  end
  for i, e in ipairs(pts) do
    map:line(lat, lon, e.lat, e.lon, i == sel and C.good or 0x2A3340, i == sel and 2 or 1)
  end
  for i, e in ipairs(pts) do
    map:marker(e.lat, e.lon, i == sel and C.good or C.accent, i == sel and 12 or 8)
  end
  map:marker(lat, lon, 0xE8A33D, 10)      -- us, last so it sits on top
end

function app.pick(i)
  sel = i
  list:select(i)
  local e = pts[i]
  if not e then return end
  local lat, lon = here()
  if e.dist then
    detail:set(string.format("%s  %s  %.0f deg (%s)  %s",
      e.name, fmt_dist(e.dist), e.brg, geo.cardinal(e.brg), e.pubkey))
  else
    detail:set(e.name .. "  " .. e.pubkey)
  end
  detail:color(C.text)
  if lat then app.draw(lat, lon) end
end

function app.on_open(w, h)
  W, H = w, h
  local LH = ui.text_h(12)
  hdr = ui.label("", 4, 4, 12, C.accent); hdr:width(w - 10)

  -- hdr and detail below are width-limited, which turns wrapping on, and both
  -- carry variable-length text (node names, a status phrase). Reserve two lines
  -- for each: a wrapped line would otherwise be drawn over by whatever follows.
  local map_h = math.floor(h * 0.45)
  local y = 4 + LH * 2 + 4
  if sys.caps().map then
    map = wada.map.view(4, y, w - 8, map_h)
  else
    ui.label("this board has no map support", 6, y + 10, 12, C.sub)
  end
  y = y + map_h + 4

  detail = ui.label("pick a contact", 4, y, 12, C.sub); detail:width(w - 10)
  y = y + LH * 2 + 4

  list = ui.list(4, y, w - 8, h - y - 4)

  rebuild()
  -- Two cadences, which is what wada.timer.after/every made possible: a slow
  -- rebuild (contacts and GPS move slowly) and no fast tick at all, because
  -- packets now arrive by callback instead of being polled for.
  timer.every(5000, rebuild)
end

-- One call per frame the radio received, in arrival order. Counting was simply
-- not possible against a polled 16-entry ring.
function app.on_packet(p)
  pkt_count = pkt_count + 1
  if p.pubkey then pkt_adverts = pkt_adverts + 1 end
end

function app.on_close()
  if map then map:close() end
end

return app
)WADALUA";

static const char kLuaSrc_wardrive[] = R"WADALUA(
-- Wardrive v1.2.1 — LoRa coverage survey with live signal map.
--
-- Three views, tap the tab bar to switch:
--   MAP    — full-screen live track coloured by best SNR (green ≥0 dB, amber ≥-10, red <-10).
--            Current GPS position shown as a dot. Updates every sweep.
--   NODES  — node table sorted by best SNR with per-node asymmetry (↓ heard us, ↑ we heard them).
--   REVIEW — reads the saved CSV back and plots the run on the map, coloured by whichever
--            link direction you ask about. Probing pauses while the review is open.
--
-- Bug fixes from upstream 1.2:
--   · wrote_header is nil-tristate: checks the file on first flush so reopening
--     an existing log never appends a second header (breaks spreadsheets).
--   · Stale harvest guard: ticks pause while the display sleeps; millis() does
--     not. Replies heard at the old position are dropped rather than mislocated.
--   · Rename flush: queued rows land in the old file before the name changes.
--
-- CSV: epoch,lat_e6,lon_e6,alt_m,pubkey,name,type,rssi,snr,their_snr,hops
local ui, sys, mesh, fs, timer = wada.ui, wada.sys, wada.mesh, wada.fs, wada.timer
local C = ui.colors
local app = {}

local clear = ui.clear or function() end
local tr    = sys.tr    or function(x) return x end

-- ── constants ────────────────────────────────────────────────────────────────
local SWEEP_MS   = 20000
local HARVEST_MS = 4000
local STALE_MS   = HARVEST_MS + 3000   -- past this, replies were heard elsewhere
local TYPE       = { [1]="chat", [2]="rep", [3]="room", [4]="sensor" }
local SNR_GOOD, SNR_OK = 0, -10

-- ── persistent survey state (survives view switches) ─────────────────────────
local function default_run_name()
  local dt = sys.datetime and sys.datetime()
  if dt then
    return string.format("wd_%04d%02d%02d_%02d%02d%02d",
      dt.year, dt.month, dt.day, dt.hour, dt.min, dt.sec)
  end
  local ep = sys.epoch and sys.epoch()
  if ep then return string.format("wd_%d", ep) end
  return "run"
end

local run, running    = default_run_name(), false
local samples, sweeps = 0, 0
local node_count      = 0
local dropped_sweeps  = 0
local last_err        = nil
local phase, phase_at = "idle", 0
local nodes   = {}   -- pubkey → { name, type, best, worst, their_snr, rssi, seen }
local pending = {}   -- write queue (fs allows 1 write/s)
local track   = {}   -- { lat, lon, snr } live breadcrumb

local function harvest_fresh(now) return (now - phase_at) <= STALE_MS end

-- ── per-view UI handles (rebuilt on every switch) ────────────────────────────
local MAP_VIEW, NODE_VIEW, REVIEW_VIEW = 1, 2, 3
local cur_view   = MAP_VIEW
local map_full   = false   -- fullscreen toggle for MAP_VIEW
local W, H = 0, 0

local map_obj    = nil   -- live survey map handle
local node_list  = nil
local status_lbl = nil
local gps_lbl    = nil
local start_btn  = nil

-- ── helpers ──────────────────────────────────────────────────────────────────
local function logname() return run .. ".csv" end

local function utf8_prefix_bytes(text, max_bytes)
  local offset, last, length = 1, 0, #text
  while offset <= length and offset <= max_bytes do
    local first = text:byte(offset)
    local width = first <= 0x7F and 1
      or (first >= 0xC2 and first <= 0xDF and 2)
      or (first >= 0xE0 and first <= 0xEF and 3)
      or (first >= 0xF0 and first <= 0xF4 and 4) or 0
    if width == 0 or offset + width - 1 > length or offset + width - 1 > max_bytes then break end
    local valid = true
    for i = 2, width do
      local byte = text:byte(offset + i - 1)
      if byte < 0x80 or byte > 0xBF then valid = false; break end
    end
    local second = width > 1 and text:byte(offset + 1) or 0
    if (first == 0xE0 and second < 0xA0) or (first == 0xED and second > 0x9F) or
       (first == 0xF0 and second < 0x90) or (first == 0xF4 and second > 0x8F) then valid = false end
    if not valid then break end
    last = offset + width - 1
    offset = last + 1
  end
  return text:sub(1, last)
end

local function snr_color(snr)
  if     snr >= SNR_GOOD then return C.good
  elseif snr >= SNR_OK   then return 0xC8A030
  else                        return C.bad end
end

-- ── CSV write queue ──────────────────────────────────────────────────────────
local HEADER = "epoch,lat_e6,lon_e6,alt_m,pubkey,name,type,rssi,snr,their_snr,hops"
-- nil = not yet checked; true/false = known. Checking on first flush prevents
-- appending a second header when reopening an existing log file.
local wrote_header = nil

local function flush()
  if #pending == 0 then return end
  local chunk = table.concat(pending, "\n") .. "\n"
  if wrote_header == nil then
    local d = fs.read(logname(), 0, 8)
    wrote_header = (d ~= nil and #d > 0)
  end
  if not wrote_header then chunk = HEADER .. "\n" .. chunk end
  if fs.append(logname(), chunk) then pending, wrote_header = {}, true end
end

local function record(fix, hit)
  local key = hit.pubkey
  local n = nodes[key]
  if not n then
    n = { name = hit.name or key:sub(1,8), type = hit.type,
          best = hit.snr, worst = hit.snr,
          their_snr = hit.their_snr, rssi = hit.rssi, seen = 0,
          last_lat = fix.lat_e6 / 1e6, last_lon = fix.lon_e6 / 1e6 }
    nodes[key] = n
    node_count = node_count + 1
  else
    if hit.snr > n.best  then n.best  = hit.snr end
    if hit.snr < n.worst then n.worst = hit.snr end
    n.their_snr = hit.their_snr
    n.rssi      = hit.rssi
    n.last_lat  = fix.lat_e6 / 1e6
    n.last_lon  = fix.lon_e6 / 1e6
    if hit.name then n.name = hit.name end
  end
  n.seen = n.seen + 1
  samples = samples + 1
  pending[#pending + 1] = string.format("%d,%d,%d,%d,%s,%s,%d,%d,%.2f,%.2f,%d",
    fix.time or sys.epoch() or 0, fix.lat_e6, fix.lon_e6, fix.alt_m or 0,
    key, (hit.name or ""):gsub(",", " "), hit.type,
    hit.rssi, hit.snr, hit.their_snr, hit.hops)
end

-- ── probe / harvest ──────────────────────────────────────────────────────────
local function do_sweep()
  local ok, err = mesh.discover()
  if not ok then last_err = err; return false end
  last_err = nil; sweeps = sweeps + 1; return true
end

local function do_harvest()
  local fix = sys.gps()
  if not fix then mesh.discover_clear(); return end
  local best_snr = nil
  for _, hit in ipairs(mesh.discovered()) do
    record(fix, hit)
    if not best_snr or hit.snr > best_snr then best_snr = hit.snr end
  end
  mesh.discover_clear()
  if fix.lat_e6 ~= 0 or fix.lon_e6 ~= 0 then
    track[#track + 1] = { lat = fix.lat_e6 / 1e6, lon = fix.lon_e6 / 1e6, snr = best_snr }
  end
end

-- ── live map / node draw ─────────────────────────────────────────────────────
local function redraw_map()
  if not map_obj then return end
  map_obj:clear()
  local fix = sys.gps()
  local my_lat = fix and fix.lat_e6 ~= 0 and fix.lat_e6 / 1e6 or nil
  local my_lon = fix and fix.lon_e6 ~= 0 and fix.lon_e6 / 1e6 or nil
  if my_lat then map_obj:center(my_lat, my_lon) end
  -- survey track coloured by best SNR at each stop
  for i = 2, #track do
    local a, b = track[i-1], track[i]
    map_obj:line(a.lat, a.lon, b.lat, b.lon, b.snr and snr_color(b.snr) or 0x444C54, 3)
  end
  -- lines from current position to last-heard position of every node
  if my_lat then
    for _, n in pairs(nodes) do
      if n.last_lat then
        map_obj:line(my_lat, my_lon, n.last_lat, n.last_lon, snr_color(n.best), 1)
        map_obj:marker(n.last_lat, n.last_lon, snr_color(n.best), 4)
      end
    end
    map_obj:marker(my_lat, my_lon, C.accent, 6)   -- self dot on top
  end
  map_obj:redraw()
end

local function redraw_nodes()
  if not node_list then return end
  node_list:clear()
  local list = {}
  for key, n in pairs(nodes) do list[#list + 1] = { key = key, n = n } end
  table.sort(list, function(a, b) return a.n.best > b.n.best end)
  if #list == 0 then node_list:add(tr("(no replies yet)"), 0, C.sub); return end
  for _, e in ipairs(list) do
    local n = e.n
    local label = string.format("%-10s %-6s  \xe2\x86\x93%+5.1f  \xe2\x86\x91%+5.1f  \xc3\x97%d",
      utf8_prefix_bytes(n.name, 10), TYPE[n.type] or "?", n.their_snr, n.best, n.seen)
    node_list:add(label, 0, snr_color(n.best))
  end
end

local function redraw_status()
  if not status_lbl then return end
  local fix = sys.gps()
  if fix and (fix.lat_e6 ~= 0 or fix.lon_e6 ~= 0) then
    gps_lbl:set(string.format("%.5f %.5f  %dm  %dsat",
      fix.lat_e6 / 1e6, fix.lon_e6 / 1e6, fix.alt_m or 0, fix.sats or 0))
    gps_lbl:color(C.good)
  else
    gps_lbl:set(tr("no GPS fix — samples discarded until locked"))
    gps_lbl:color(C.bad)
  end
  local state_str
  if not running then
    state_str = tr("stopped")
  elseif phase == "probe" then
    state_str = tr("listening…")
  else
    local rem = math.max(0, SWEEP_MS - (sys.millis() - phase_at))
    state_str = string.format(tr("next probe %ds"), math.ceil(rem / 1000))
  end
  status_lbl:set(string.format("%s  •  %d sweeps  %d nodes%s%s",
    state_str, sweeps, node_count,
    dropped_sweeps > 0 and ("  · " .. dropped_sweeps .. " dropped") or "",
    last_err and ("  [⚠ " .. last_err .. "]") or ""))
  status_lbl:color(last_err and C.bad or (running and C.accent or C.sub))
end

-- ── ⚠️ drop_map MUST be called before any ui.clear() ────────────────────────
-- The map userdata has no generation field: clear() deletes its container but
-- leaves the one-view counter set and the pointer live. Closing first avoids
-- leaking tile pixels, a stuck "only one map view" error, and a later UAF.
local function drop_map()
  if map_obj then pcall(function() map_obj:close() end); map_obj = nil end
end

-- ── review state ─────────────────────────────────────────────────────────────
local MODES = { tr("heard them"), tr("heard us"), tr("asymmetry") }
local mode   = 1
local was_running = false
local rv_map, rv_map_note, rv_stat, rv_legend, rv_plot = nil, nil, nil, nil, nil
local plot_px = 0
local ld      = nil
local READ_WIN = 4096
local MAX_DRAW = 150

local function metric_of(st)
  if mode == 2 then return st.them_max end
  if mode == 3 then return st.asym     end
  return st.snr_max
end

local function colour_for(v)
  if mode == 3 then
    if v > 6 or v < -6 then return C.bad end
    if v > 3 or v < -3 then return C.accent end
    return C.good
  end
  if v >= 0   then return C.good   end
  if v >= -10 then return C.accent end
  return C.bad
end

local function ld_reset()
  ld = { off=0, total=nil, tail="", stops={}, n=0, skipped=0, done=false, plotted=false,
         minlat=nil, maxlat=nil, minlon=nil, maxlon=nil, metres=0, wrapped=false,
         prev_lat=nil, prev_lon=nil, by_node={}, node_n=0, step=1,
         stop_n=0, pos_i=0, keep_every=1, last_key=nil, cur=nil, tailstop=nil }
end

local MAX_STOPS = 400
local function stop_push(lat, lon)
  ld.pos_i  = ld.pos_i  + 1
  ld.stop_n = ld.stop_n + 1
  if #ld.stops >= MAX_STOPS then
    local last = ld.stops[#ld.stops]
    local out, j = {}, 0
    for i = 1, #ld.stops, 2 do j = j + 1; out[j] = ld.stops[i] end
    if out[j] ~= last then j = j + 1; out[j] = last end
    ld.stops = out
    ld.keep_every = ld.keep_every * 2
  end
  local st = { lat=lat, lon=lon, n=0 }
  ld.tailstop = st
  if (ld.pos_i % ld.keep_every) == 0 then
    ld.stops[#ld.stops + 1] = st; st.kept = true
  end
  return st
end

local function stops_finalise()
  local t = ld and ld.tailstop
  if t and not t.kept and #ld.stops > 0 then
    ld.stops[#ld.stops + 1] = t; t.kept = true
  end
end

local function ld_row(line)
  local f, n = {}, 0
  for part in (line .. ","):gmatch("([^,]*),") do
    n = n + 1; f[n] = part; if n >= 11 then break end
  end
  if n < 11 then ld.skipped = ld.skipped + 1; return end
  local lat_e6, lon_e6 = tonumber(f[2]), tonumber(f[3])
  local snr, their     = tonumber(f[9]), tonumber(f[10])
  if not (lat_e6 and lon_e6 and snr and their) then ld.skipped = ld.skipped + 1; return end
  local lat, lon = lat_e6 / 1000000, lon_e6 / 1000000
  if lat_e6 == 0 and lon_e6 == 0 then ld.skipped = ld.skipped + 1; return end
  ld.n = ld.n + 1
  if not ld.minlat or lat < ld.minlat then ld.minlat = lat end
  if not ld.maxlat or lat > ld.maxlat then ld.maxlat = lat end
  if not ld.minlon or lon < ld.minlon then ld.minlon = lon end
  if not ld.maxlon or lon > ld.maxlon then ld.maxlon = lon end
  if ld.prev_lat and wada.geo then
    local ok, d = pcall(wada.geo.distance, ld.prev_lat, ld.prev_lon, lat, lon)
    if ok and d then ld.metres = ld.metres + d end
  end
  ld.prev_lat, ld.prev_lon = lat, lon
  local key = f[5]
  local nd = ld.by_node[key]
  if not nd then
    nd = { name=(f[6] ~= "" and f[6]) or key, type=tonumber(f[7]) or 0,
           best=snr, worst=snr, best_them=their, asym=snr-their, seen=0 }
    ld.by_node[key] = nd; ld.node_n = ld.node_n + 1
  end
  if snr  > nd.best      then nd.best      = snr   end
  if snr  < nd.worst     then nd.worst     = snr   end
  if their > nd.best_them then nd.best_them = their end
  do
    local a = snr - their
    if (a < 0 and -a or a) > (nd.asym < 0 and -nd.asym or nd.asym) then nd.asym = a end
  end
  nd.seen = nd.seen + 1
  local ekey = f[2] .. "," .. f[3]
  if ekey ~= ld.last_key then ld.last_key = ekey; ld.cur = stop_push(lat, lon) end
  local st = ld.cur
  if st then
    st.n = st.n + 1
    if not st.snr_max  or snr   > st.snr_max  then st.snr_max  = snr   end
    if not st.snr_min  or snr   < st.snr_min  then st.snr_min  = snr   end
    if not st.them_max or their > st.them_max  then st.them_max = their end
    if not st.them_min or their < st.them_min  then st.them_min = their end
    local a = snr - their
    if not st.asym or (a < 0 and -a or a) > (st.asym < 0 and -st.asym or st.asym) then st.asym = a end
  end
end

local function ld_step()
  if not ld or ld.done then return false end
  local data = fs.read(logname(), ld.off, READ_WIN)
  if not data then
    if ld.tail ~= "" and not ld.tail:find("^epoch,") then ld_row(ld.tail); ld.tail = "" end
    stops_finalise(); ld.done = true; return false
  end
  ld.off = ld.off + #data
  local buf  = ld.tail .. data
  local last = 0
  for line, pos in buf:gmatch("([^\n]*)\n()") do
    last = pos - 1
    if line ~= "" and not line:find("^epoch,") then ld_row(line) end
  end
  ld.tail = buf:sub(last + 1)
  if #data == 0 then
    if ld.tail ~= "" and not ld.tail:find("^epoch,") then ld_row(ld.tail) end
    ld.tail = ""; stops_finalise(); ld.done = true
  end
  return not ld.done
end

local function merc_y(lat)
  if lat >  85 then lat =  85 end
  if lat < -85 then lat = -85 end
  local r = lat * math.pi / 180
  return 0.5 - math.log(math.tan(math.pi / 4 + r / 2)) / (2 * math.pi)
end
local function merc_lat(y)
  local r = 2 * (math.atan(math.exp((0.5 - y) * 2 * math.pi)) - math.pi / 4)
  return r * 180 / math.pi
end

local function fit_zoom(px, py)
  if not ld or not ld.minlat then return 14 end
  local sy = math.max(math.abs(merc_y(ld.minlat) - merc_y(ld.maxlat)), 1e-9)
  local sx  = (ld.maxlon - ld.minlon) / 360
  if sx > 0.5 then ld.wrapped = true end
  sx = math.max(sx, 1e-9)
  local function z_for(span, pixels)
    if not (pixels > 0) then return 1 end
    local v = pixels / (256 * span)
    if not (v > 1) then return 1 end
    return math.floor(math.log(v) / math.log(2))
  end
  local z = ld.wrapped and z_for(sy, py) or math.min(z_for(sx, px), z_for(sy, py))
  if not (z == z) then z = 14 end
  if z < 1 then z = 1 end; if z > 19 then z = 19 end
  return z
end

local function review_plot()
  if not ld then return end
  local drawn = 0
  local step  = math.max(1, math.ceil(#ld.stops / MAX_DRAW))
  ld.step = step
  if rv_map then
    rv_map:clear()
    if ld.minlat then
      local clat = merc_lat((merc_y(ld.minlat) + merc_y(ld.maxlat)) / 2)
      local clon
      if ld.wrapped then
        local a = ld.minlon < 0 and ld.minlon + 360 or ld.minlon
        local b = ld.maxlon < 0 and ld.maxlon + 360 or ld.maxlon
        clon = (a + b) / 2; if clon > 180 then clon = clon - 360 end
      else
        clon = (ld.minlon + ld.maxlon) / 2
      end
      rv_map:center(clat, clon, fit_zoom(W - 8, plot_px))
      local prev = nil
      for i = 1, #ld.stops, step do
        local st = ld.stops[i]
        if prev then rv_map:line(prev.lat, prev.lon, st.lat, st.lon, C.sub, 1) end
        if rv_map:marker(st.lat, st.lon, colour_for(metric_of(st)), 3) then drawn = drawn + 1 end
        prev = st
      end
    end
    local tiles = 0
    local ok, t = pcall(function() return rv_map:tiles() end)
    if ok and t then tiles = t end
    if not ld.minlat then
      rv_map_note:set("")
    elseif tiles == 0 then
      rv_map_note:set(tr("no tiles cached here - blank ground, not open water")); rv_map_note:color(C.bad)
    else
      rv_map_note:set(string.format("%d tiles  ·  %d of %d stops%s%s", tiles, drawn, ld.stop_n,
        step > 1 and ("  ·  1 in " .. step) or "",
        ld.keep_every > 1 and ("  ·  sampled 1 in " .. ld.keep_every) or ""))
      rv_map_note:color(C.sub)
    end
  elseif rv_plot then
    local pw = math.min(W - 8, 480); local ph = math.min(plot_px, 480)
    rv_plot:fill(C.bg)
    if ld.minlat then
      local dlat = math.max(ld.maxlat - ld.minlat, 1e-6)
      local dlon = math.max(ld.maxlon - ld.minlon, 1e-6)
      local function sx(lon) return math.floor(4 + (lon - ld.minlon) / dlon * (pw - 8)) end
      local function sy(lat) return math.floor(4 + (ld.maxlat - lat) / dlat * (ph - 8)) end
      local prev = nil
      for i = 1, #ld.stops, step do
        local st = ld.stops[i]; local x, y = sx(st.lon), sy(st.lat)
        if prev then rv_plot:line(prev[1], prev[2], x, y, C.sub) end
        rv_plot:circle(x, y, 2, colour_for(metric_of(st))); drawn = drawn + 1; prev = {x, y}
      end
    end
    rv_plot:text(4, 2, string.format(tr("route shape - %d of %d stops"), drawn, ld.stop_n), C.sub, 12)
  end
end

local function review_stat()
  if not ld then return end
  if not ld.done then
    rv_stat:set(string.format(tr("reading %s … %d rows"), logname(), ld.n)); rv_stat:color(C.sub); return
  end
  if ld.n == 0 then
    rv_stat:set(string.format(tr("%s has no plottable rows yet"), logname())); rv_stat:color(C.bad); return
  end
  rv_stat:set(string.format("%s  ·  %d samples, %d stops, %d nodes  ·  %.2f km%s%s",
    run, ld.n, ld.stop_n, ld.node_n, ld.metres / 1000,
    ld.wrapped and "  ·  crosses antimeridian" or "",
    ld.skipped > 0 and ("  ·  " .. ld.skipped .. " unusable") or ""))
  rv_stat:color(C.accent)
  local worst_name, worst_gap = nil, nil
  for _, nd in pairs(ld.by_node) do
    local g = nd.asym < 0 and -nd.asym or nd.asym
    if not worst_gap or g > worst_gap then worst_gap, worst_name = g, nd.name end
  end
  local legend
  if mode == 3 then
    legend = tr("colour: balance — green even, red one-sided")
    if worst_name then
      legend = legend .. string.format("  ·  worst %s %.1f dB", utf8_prefix_bytes(worst_name, 10), worst_gap)
    end
  elseif mode == 2 then legend = tr("colour: how well they heard US")
  else                  legend = tr("colour: how well WE heard them") end
  rv_legend:set(legend); rv_legend:color(C.sub)
end

-- ── view builder ─────────────────────────────────────────────────────────────
local function build_view(v)
  if v ~= MAP_VIEW then map_full = false end
  cur_view = v
  drop_map()   -- MUST precede clear()
  clear()
  node_list, status_lbl, gps_lbl, start_btn = nil, nil, nil, nil
  rv_map, rv_map_note, rv_stat, rv_legend, rv_plot = nil, nil, nil, nil, nil

  local LH = ui.text_h(12)
  local y  = 2
  local has_map = sys.caps().map

  gps_lbl    = ui.label("", 4, y, 12, C.sub);    gps_lbl:width(W - 8);    y = y + LH + 2
  status_lbl = ui.label("", 4, y, 12, C.accent); status_lbl:width(W - 8); y = y + LH + 3

  -- control row
  local bw = math.min(80, (W - 16) // 3)
  start_btn = ui.button(running and tr("Stop") or tr("Start"), 4, y, bw, 26, function()
    running = not running
    if running then phase, phase_at = "idle", 0 end
    start_btn:set(running and tr("Stop") or tr("Start"))
    sys.toast(running and tr("Survey running") or tr("Survey stopped"), 1000)
  end)
  ui.button(tr("Name"), 8 + bw, y, bw, 26, function()
    ui.input(tr("Name this run"), run, function(text)
      if text and text ~= "" then
        flush()                              -- land queued rows into the OLD file first
        pending      = {}                    -- anything the rate limit refused belongs to old run
        run          = text:gsub("[^%w%-_]", "_")
        wrote_header = nil                   -- unknown: new file may or may not have a header
        sys.toast(tr("Logging to ") .. logname(), 1500)
      end
    end)
  end)
  ui.button(tr("Reset"), 12 + bw * 2, y, bw, 26, function()
    nodes, samples, sweeps, pending, node_count = {}, 0, 0, {}, 0
    dropped_sweeps = 0; track = {}; mesh.discover_clear()
    fs.remove(logname()); wrote_header = nil
    run = default_run_name()
    sys.toast(tr("Cleared — new run: ") .. run, 1500)
  end)
  y = y + 30

  -- tab bar
  local tabs = has_map and { tr("Map"), tr("Nodes"), tr("Review") }
                        or { tr("Nodes"), tr("Review") }
  local tab_views = has_map and { MAP_VIEW, NODE_VIEW, REVIEW_VIEW }
                             or { NODE_VIEW, REVIEW_VIEW }
  local tw = (W - 8 - (#tabs - 1) * 4) // #tabs
  for i, label in ipairs(tabs) do
    local tv = tab_views[i]
    local x  = 4 + (i - 1) * (tw + 4)
    local btn = ui.button(label, x, y, tw, 24, function() build_view(tv) end)
    btn:color(v == tv and C.accent or C.sub)
  end
  y = y + 28

  local content_h = H - y - 2

  if v == MAP_VIEW and has_map then
    -- fullscreen: map fills entire body, skip header/tab rows
    local mx, my, mw, mh
    if map_full then
      mx, my, mw, mh = 0, 0, W, H
    else
      mx, my, mw, mh = 4, y, W - 8, content_h
    end
    map_obj = wada.map.view(mx, my, mw, mh)
    local fix = sys.gps()
    if fix and (fix.lat_e6 ~= 0 or fix.lon_e6 ~= 0) then
      map_obj:center(fix.lat_e6 / 1e6, fix.lon_e6 / 1e6, 13)
    else
      map_obj:zoom(13)
    end
    -- fullscreen toggle button: floating top-right corner over the map
    ui.button(map_full and "[-]" or "[+]", W - 32, 2, 28, 22, function()
      map_full = not map_full
      build_view(MAP_VIEW)
    end)
    redraw_map()

  elseif v == NODE_VIEW then
    node_list = ui.list(4, y, W - 8, content_h, function(_idx) end)
    redraw_nodes()

  elseif v == REVIEW_VIEW then
    -- bank in-flight probe before pausing
    if running and phase == "probe" and harvest_fresh(sys.millis()) then
      do_harvest()
    else
      if phase == "probe" then dropped_sweeps = dropped_sweeps + 1 end
      mesh.discover_clear()
    end
    flush()
    was_running = running
    running = false; phase = "idle"
    ld_reset()
    -- stat line
    rv_stat = ui.label("", 4, y, 12, C.text); rv_stat:width(W - 8)
    y = y + LH + 3
    -- reserve bottom rows, give map/plot the rest
    local BTN_H  = 28
    local footer = (LH + 2) + (LH + 2) + BTN_H + 4
    local plot_h = math.max(40, content_h - (LH + 3) - footer)
    plot_px      = plot_h
    if has_map then
      local ok, m = pcall(function() return wada.map.view(4, y, W - 8, plot_h) end)
      if ok and m then rv_map = m end
    end
    if not rv_map then
      local okc, cv = pcall(ui.canvas, math.min(W - 8, 480), math.min(plot_h, 480))
      if okc and cv then rv_plot = cv; rv_plot:pos(4, y) end
    end
    y = y + plot_h + 4
    rv_map_note = ui.label("", 4, y, 12, C.sub); rv_map_note:width(W - 8); y = y + LH + 2
    rv_legend   = ui.label("", 4, y, 12, C.sub); rv_legend:width(W - 8);   y = y + LH + 2
    local rbw = math.min(80, (W - 16) // 3)
    -- Back: restore running state
    ui.button(tr("Back"), 4, y, rbw, BTN_H, function()
      if rv_map then pcall(function() rv_map:close() end); rv_map = nil end
      running = was_running
      if running then phase, phase_at = "idle", 0 end
      mesh.discover_clear()
      ld = nil
      build_view(has_map and MAP_VIEW or NODE_VIEW)
    end)
    ui.button(tr("Colour"), 8 + rbw, y, rbw, BTN_H, function()
      mode = mode % #MODES + 1
      sys.toast(MODES[mode], 800)
      review_plot(); review_stat()
    end)
    ui.button(tr("Refit"), 12 + rbw * 2, y, rbw, BTN_H, function()
      ld_reset(); review_stat()
    end)
    review_stat()
  end

  redraw_status()
end

-- ── app callbacks ─────────────────────────────────────────────────────────────
function app.on_open(w, h)
  if not sys.caps().discover then
    ui.label(tr("This board cannot send discovery probes,"), 6,  8, 12, C.bad)
    ui.label(tr("so it cannot run a coverage survey."),     6, 26, 12, C.bad)
    return
  end
  W, H = w, h
  ui.scroll(false)
  build_view(sys.caps().map and MAP_VIEW or NODE_VIEW)
  timer.every(1000)
end

function app.on_tick()
  if cur_view == REVIEW_VIEW then
    local more = ld_step()
    review_stat()
    if not more and ld and ld.done and not ld.plotted then
      ld.plotted = true; review_plot()
    end
    flush()
    return
  end

  local map_redrawn = false
  if running then
    local now = sys.millis()
    if phase == "idle" or (phase == "wait" and now - phase_at >= SWEEP_MS) then
      phase, phase_at = do_sweep() and "probe" or "wait", now
    elseif phase == "probe" and now - phase_at >= HARVEST_MS then
      if harvest_fresh(now) then
        do_harvest()
        if cur_view == MAP_VIEW  then redraw_map(); map_redrawn = true end
        if cur_view == NODE_VIEW then redraw_nodes() end
      else
        mesh.discover_clear(); dropped_sweeps = dropped_sweeps + 1
      end
      phase = "wait"
    end
  end
  flush()
  redraw_status()
  -- keep position dot moving between sweeps (skip if redraw_map() already ran this tick)
  if map_obj and not map_redrawn then
    local fix = sys.gps()
    if fix and (fix.lat_e6 ~= 0 or fix.lon_e6 ~= 0) then
      map_obj:center(fix.lat_e6 / 1e6, fix.lon_e6 / 1e6)  -- center() renders internally, no extra :redraw()
    end
  end
end

function app.on_close()
  flush()
  drop_map()
  if rv_map then pcall(function() rv_map:close() end); rv_map = nil end
end

return app
)WADALUA";

static const LuaBuiltinApp kLuaBuiltin[] = {
  { "monitor",  "RF Monitor", "1.3",   kLuaSrc_monitor  },
  { "airtime",  "Airtime",    "1.4",   kLuaSrc_airtime  },
  { "sdktest",  "SDK Test",   "1.7",   kLuaSrc_sdktest  },
  { "nearby",   "Nearby",     "1.0",   kLuaSrc_nearby   },
  { "wardrive", "Wardrive",   "1.2.1", kLuaSrc_wardrive },
};
static const int kLuaBuiltinCount = (int)(sizeof(kLuaBuiltin)/sizeof(kLuaBuiltin[0]));
